// Generated by scripts/generate_contracts.py. Edit Python contracts, then regenerate.
// Internal tickets, sessions and leases are intentionally excluded.

/** @typedef {Object} BackupManifest
 * @property {number} format_version
 * @property {string} schema_revision
 * @property {StorageBackend} backend
 * @property {string} profile_id
 * @property {Object<string, string>} checksums
 * @property {string} vector_state
 */

/** @typedef {"telegram_account"|"control_bot"|"chat_ai"|"embeddings"|"storage"|"runtime"} ConnectionService */

/** @typedef {"checking"|"ready"|"degraded"|"disconnected"|"unknown"} ConnectionState */

/** @typedef {Object} ConnectionStatus
 * @property {ConnectionService} service
 * @property {ConnectionState} state
 * @property {(string|null)} checked_at
 * @property {string} code
 * @property {string} message
 * @property {(string|null)} next_action
 * @property {Array<string>} capabilities
 */

/** @typedef {Object} EmbeddingProfile
 * @property {string} provider
 * @property {(string|null)} endpoint_id
 * @property {string} model
 * @property {string} embedding_version
 * @property {number} dimension
 * @property {string} store_id
 * @property {boolean} cloud_consent
 */

/** @typedef {unknown} JsonValue */

/** @typedef {Object} MigrationReport
 * @property {(string|null)} previous_revision
 * @property {string} current_revision
 * @property {boolean} changed
 * @property {string} code
 * @property {(string|null)} next_action
 */

/** @typedef {Object} NativeCommand
 * @property {NativeCommandName} name
 * @property {string} request_id
 * @property {string} profile_id
 * @property {Object<string, JsonValue>} payload_nonsecret
 */

/** @typedef {"open_connection_dialog"|"open_telegram_login"|"open_bot_dialog"|"issue_dashboard_ticket"|"runtime_start"|"runtime_stop"} NativeCommandName */

/** @typedef {"welcome"|"storage_ready"|"ai_configured"|"telegram_verified"|"bot_verified"|"owner_paired"|"source_selected"|"first_answer"|"ready"} OnboardingStage */

/** @typedef {Object} OnboardingStatus
 * @property {PublicProfile} profile
 * @property {Array<ConnectionStatus>} connections
 * @property {Object<string, string>} stage_evidence_ids
 * @property {(string|null)} next_action
 * @property {Array<string>} disabled_capabilities
 */

/** @typedef {Object} OperationResult
 * @property {string} operation_id
 * @property {OperationState} state
 * @property {(number|null)} progress
 * @property {string} code
 * @property {string} message
 * @property {(string|null)} next_action
 */

/** @typedef {"queued"|"running"|"paused"|"completed"|"completed_with_warning"|"failed"|"cancelled"|"uncertain"} OperationState */

/** @typedef {Object} PublicProfile
 * @property {string} profile_id
 * @property {(string|null)} owner_id
 * @property {StorageBackend} storage_backend
 * @property {OnboardingStage} setup_stage
 * @property {number} version
 */

/** @typedef {Object} RecoveryPlan
 * @property {string} plan_id
 * @property {string} chat_id
 * @property {string} store_id
 * @property {number} authorization_epoch
 * @property {number} index_generation
 * @property {number} expected_count
 * @property {string} expires_at
 */

/** @typedef {Object} RevocationReport
 * @property {string} chat_id
 * @property {number} authorization_epoch
 * @property {number} cancelled_jobs
 * @property {string} memory_action
 * @property {(string|null)} operation_id
 */

/** @typedef {"sqlite"} StorageBackend */

export const contractSchema = {
  "contracts": {
    "BackupManifest": {
      "$defs": {
        "StorageBackend": {
          "enum": [
            "sqlite"
          ],
          "title": "StorageBackend",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "properties": {
        "backend": {
          "$ref": "#/$defs/StorageBackend"
        },
        "checksums": {
          "additionalProperties": {
            "pattern": "^[a-f0-9]{64}$",
            "type": "string"
          },
          "title": "Checksums",
          "type": "object"
        },
        "format_version": {
          "minimum": 1,
          "title": "Format Version",
          "type": "integer"
        },
        "profile_id": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Profile Id",
          "type": "string"
        },
        "schema_revision": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Schema Revision",
          "type": "string"
        },
        "vector_state": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Vector State",
          "type": "string"
        }
      },
      "required": [
        "format_version",
        "schema_revision",
        "backend",
        "profile_id",
        "checksums",
        "vector_state"
      ],
      "title": "BackupManifest",
      "type": "object"
    },
    "ConnectionStatus": {
      "$defs": {
        "ConnectionService": {
          "enum": [
            "telegram_account",
            "control_bot",
            "chat_ai",
            "embeddings",
            "storage",
            "runtime"
          ],
          "title": "ConnectionService",
          "type": "string"
        },
        "ConnectionState": {
          "enum": [
            "checking",
            "ready",
            "degraded",
            "disconnected",
            "unknown"
          ],
          "title": "ConnectionState",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "properties": {
        "capabilities": {
          "items": {
            "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
            "type": "string"
          },
          "title": "Capabilities",
          "type": "array"
        },
        "checked_at": {
          "anyOf": [
            {
              "format": "date-time",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Checked At"
        },
        "code": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Code",
          "type": "string"
        },
        "message": {
          "maxLength": 2048,
          "title": "Message",
          "type": "string"
        },
        "next_action": {
          "anyOf": [
            {
              "maxLength": 2048,
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Next Action"
        },
        "service": {
          "$ref": "#/$defs/ConnectionService"
        },
        "state": {
          "$ref": "#/$defs/ConnectionState"
        }
      },
      "required": [
        "service",
        "state",
        "checked_at",
        "code",
        "message",
        "next_action",
        "capabilities"
      ],
      "title": "ConnectionStatus",
      "type": "object"
    },
    "EmbeddingProfile": {
      "additionalProperties": false,
      "properties": {
        "cloud_consent": {
          "title": "Cloud Consent",
          "type": "boolean"
        },
        "dimension": {
          "minimum": 1,
          "title": "Dimension",
          "type": "integer"
        },
        "embedding_version": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Embedding Version",
          "type": "string"
        },
        "endpoint_id": {
          "anyOf": [
            {
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Endpoint Id"
        },
        "model": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Model",
          "type": "string"
        },
        "provider": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Provider",
          "type": "string"
        },
        "store_id": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Store Id",
          "type": "string"
        }
      },
      "required": [
        "provider",
        "endpoint_id",
        "model",
        "embedding_version",
        "dimension",
        "store_id",
        "cloud_consent"
      ],
      "title": "EmbeddingProfile",
      "type": "object"
    },
    "MigrationReport": {
      "additionalProperties": false,
      "properties": {
        "changed": {
          "title": "Changed",
          "type": "boolean"
        },
        "code": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Code",
          "type": "string"
        },
        "current_revision": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Current Revision",
          "type": "string"
        },
        "next_action": {
          "anyOf": [
            {
              "maxLength": 2048,
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Next Action"
        },
        "previous_revision": {
          "anyOf": [
            {
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Previous Revision"
        }
      },
      "required": [
        "previous_revision",
        "current_revision",
        "changed",
        "code",
        "next_action"
      ],
      "title": "MigrationReport",
      "type": "object"
    },
    "NativeCommand": {
      "$defs": {
        "JsonValue": {},
        "NativeCommandName": {
          "enum": [
            "open_connection_dialog",
            "open_telegram_login",
            "open_bot_dialog",
            "issue_dashboard_ticket",
            "runtime_start",
            "runtime_stop"
          ],
          "title": "NativeCommandName",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "properties": {
        "name": {
          "$ref": "#/$defs/NativeCommandName"
        },
        "payload_nonsecret": {
          "additionalProperties": {
            "$ref": "#/$defs/JsonValue"
          },
          "title": "Payload Nonsecret",
          "type": "object",
          "x-native-payload": true
        },
        "profile_id": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Profile Id",
          "type": "string"
        },
        "request_id": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Request Id",
          "type": "string"
        }
      },
      "required": [
        "name",
        "request_id",
        "profile_id",
        "payload_nonsecret"
      ],
      "title": "NativeCommand",
      "type": "object"
    },
    "OnboardingStatus": {
      "$defs": {
        "ConnectionService": {
          "enum": [
            "telegram_account",
            "control_bot",
            "chat_ai",
            "embeddings",
            "storage",
            "runtime"
          ],
          "title": "ConnectionService",
          "type": "string"
        },
        "ConnectionState": {
          "enum": [
            "checking",
            "ready",
            "degraded",
            "disconnected",
            "unknown"
          ],
          "title": "ConnectionState",
          "type": "string"
        },
        "ConnectionStatus": {
          "additionalProperties": false,
          "properties": {
            "capabilities": {
              "items": {
                "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
                "type": "string"
              },
              "title": "Capabilities",
              "type": "array"
            },
            "checked_at": {
              "anyOf": [
                {
                  "format": "date-time",
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Checked At"
            },
            "code": {
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
              "title": "Code",
              "type": "string"
            },
            "message": {
              "maxLength": 2048,
              "title": "Message",
              "type": "string"
            },
            "next_action": {
              "anyOf": [
                {
                  "maxLength": 2048,
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Next Action"
            },
            "service": {
              "$ref": "#/$defs/ConnectionService"
            },
            "state": {
              "$ref": "#/$defs/ConnectionState"
            }
          },
          "required": [
            "service",
            "state",
            "checked_at",
            "code",
            "message",
            "next_action",
            "capabilities"
          ],
          "title": "ConnectionStatus",
          "type": "object"
        },
        "OnboardingStage": {
          "enum": [
            "welcome",
            "storage_ready",
            "ai_configured",
            "telegram_verified",
            "bot_verified",
            "owner_paired",
            "source_selected",
            "first_answer",
            "ready"
          ],
          "title": "OnboardingStage",
          "type": "string"
        },
        "PublicProfile": {
          "additionalProperties": false,
          "properties": {
            "owner_id": {
              "anyOf": [
                {
                  "pattern": "^[1-9][0-9]*$",
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Owner Id"
            },
            "profile_id": {
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
              "title": "Profile Id",
              "type": "string"
            },
            "setup_stage": {
              "$ref": "#/$defs/OnboardingStage"
            },
            "storage_backend": {
              "$ref": "#/$defs/StorageBackend"
            },
            "version": {
              "minimum": 1,
              "title": "Version",
              "type": "integer"
            }
          },
          "required": [
            "profile_id",
            "owner_id",
            "storage_backend",
            "setup_stage",
            "version"
          ],
          "title": "PublicProfile",
          "type": "object"
        },
        "StorageBackend": {
          "enum": [
            "sqlite"
          ],
          "title": "StorageBackend",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "properties": {
        "connections": {
          "items": {
            "$ref": "#/$defs/ConnectionStatus"
          },
          "title": "Connections",
          "type": "array"
        },
        "disabled_capabilities": {
          "items": {
            "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
            "type": "string"
          },
          "title": "Disabled Capabilities",
          "type": "array"
        },
        "next_action": {
          "anyOf": [
            {
              "maxLength": 2048,
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Next Action"
        },
        "profile": {
          "$ref": "#/$defs/PublicProfile"
        },
        "stage_evidence_ids": {
          "additionalProperties": {
            "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
            "type": "string"
          },
          "propertyNames": {
            "$ref": "#/$defs/OnboardingStage"
          },
          "title": "Stage Evidence Ids",
          "type": "object"
        }
      },
      "required": [
        "profile",
        "connections",
        "stage_evidence_ids",
        "next_action",
        "disabled_capabilities"
      ],
      "title": "OnboardingStatus",
      "type": "object"
    },
    "OperationResult": {
      "$defs": {
        "OperationState": {
          "enum": [
            "queued",
            "running",
            "paused",
            "completed",
            "completed_with_warning",
            "failed",
            "cancelled",
            "uncertain"
          ],
          "title": "OperationState",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "properties": {
        "code": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Code",
          "type": "string"
        },
        "message": {
          "maxLength": 2048,
          "title": "Message",
          "type": "string"
        },
        "next_action": {
          "anyOf": [
            {
              "maxLength": 2048,
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Next Action"
        },
        "operation_id": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Operation Id",
          "type": "string"
        },
        "progress": {
          "anyOf": [
            {
              "maximum": 100,
              "minimum": 0,
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "title": "Progress"
        },
        "state": {
          "$ref": "#/$defs/OperationState"
        }
      },
      "required": [
        "operation_id",
        "state",
        "progress",
        "code",
        "message",
        "next_action"
      ],
      "title": "OperationResult",
      "type": "object"
    },
    "PublicProfile": {
      "$defs": {
        "OnboardingStage": {
          "enum": [
            "welcome",
            "storage_ready",
            "ai_configured",
            "telegram_verified",
            "bot_verified",
            "owner_paired",
            "source_selected",
            "first_answer",
            "ready"
          ],
          "title": "OnboardingStage",
          "type": "string"
        },
        "StorageBackend": {
          "enum": [
            "sqlite"
          ],
          "title": "StorageBackend",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "properties": {
        "owner_id": {
          "anyOf": [
            {
              "pattern": "^[1-9][0-9]*$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Owner Id"
        },
        "profile_id": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Profile Id",
          "type": "string"
        },
        "setup_stage": {
          "$ref": "#/$defs/OnboardingStage"
        },
        "storage_backend": {
          "$ref": "#/$defs/StorageBackend"
        },
        "version": {
          "minimum": 1,
          "title": "Version",
          "type": "integer"
        }
      },
      "required": [
        "profile_id",
        "owner_id",
        "storage_backend",
        "setup_stage",
        "version"
      ],
      "title": "PublicProfile",
      "type": "object"
    },
    "RecoveryPlan": {
      "additionalProperties": false,
      "properties": {
        "authorization_epoch": {
          "minimum": 0,
          "title": "Authorization Epoch",
          "type": "integer"
        },
        "chat_id": {
          "pattern": "^-?[1-9][0-9]*$",
          "title": "Chat Id",
          "type": "string"
        },
        "expected_count": {
          "minimum": 0,
          "title": "Expected Count",
          "type": "integer"
        },
        "expires_at": {
          "format": "date-time",
          "title": "Expires At",
          "type": "string"
        },
        "index_generation": {
          "minimum": 0,
          "title": "Index Generation",
          "type": "integer"
        },
        "plan_id": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Plan Id",
          "type": "string"
        },
        "store_id": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Store Id",
          "type": "string"
        }
      },
      "required": [
        "plan_id",
        "chat_id",
        "store_id",
        "authorization_epoch",
        "index_generation",
        "expected_count",
        "expires_at"
      ],
      "title": "RecoveryPlan",
      "type": "object"
    },
    "RevocationReport": {
      "additionalProperties": false,
      "properties": {
        "authorization_epoch": {
          "minimum": 0,
          "title": "Authorization Epoch",
          "type": "integer"
        },
        "cancelled_jobs": {
          "minimum": 0,
          "title": "Cancelled Jobs",
          "type": "integer"
        },
        "chat_id": {
          "pattern": "^-?[1-9][0-9]*$",
          "title": "Chat Id",
          "type": "string"
        },
        "memory_action": {
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
          "title": "Memory Action",
          "type": "string"
        },
        "operation_id": {
          "anyOf": [
            {
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Operation Id"
        }
      },
      "required": [
        "chat_id",
        "authorization_epoch",
        "cancelled_jobs",
        "memory_action",
        "operation_id"
      ],
      "title": "RevocationReport",
      "type": "object"
    }
  },
  "native_payload_max_bytes": 8192,
  "native_payload_max_depth": 16,
  "native_target_keys": [
    "path",
    "url",
    "uri",
    "executable",
    "command",
    "shell",
    "args",
    "argv"
  ],
  "sensitive_key_parts": [
    "secret",
    "password",
    "token",
    "apikey",
    "apihash",
    "credential",
    "authorization",
    "otp",
    "twofactor",
    "2fa",
    "rawticket",
    "claimtoken",
    "session",
    "cookie"
  ],
  "unverified_stages": [
    "welcome",
    "storage_ready",
    "ai_configured"
  ],
  "version": 2
}

const own = (value, key) => Object.prototype.hasOwnProperty.call(value, key)

function nonsecretPayload(value, depth = 0) {
  if (depth > contractSchema.native_payload_max_depth) return false
  if (Array.isArray(value)) return value.every((child) => nonsecretPayload(child, depth + 1))
  if (value !== null && typeof value === 'object') {
    if (Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null) return false
    return Object.entries(value).every(([key, child]) => {
      const normalized = key.toLowerCase().replace(/[^a-z0-9]/g, '')
      return !contractSchema.sensitive_key_parts.some((part) => normalized.includes(part))
        && !contractSchema.native_target_keys.some((part) => normalized.includes(part))
        && nonsecretPayload(child, depth + 1)
    })
  }
  if (typeof value === 'string') return !/[A-Za-z][A-Za-z0-9+.-]*:\/\//.test(value)
  return value === null || typeof value === 'boolean' || (typeof value === 'number' && Number.isFinite(value))
}

function timestamp(value) {
  const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(?:Z|[+-](\d{2}):(\d{2}))$/.exec(value)
  if (!match || !Number.isFinite(Date.parse(value))) return false
  const [, year, month, day, hour, minute, second, offsetHour = '0', offsetMinute = '0'] = match
  const days = new Date(Date.UTC(Number(year), Number(month), 0)).getUTCDate()
  return Number(month) >= 1 && Number(month) <= 12 && Number(day) >= 1 && Number(day) <= days
    && Number(hour) <= 23 && Number(minute) <= 59 && Number(second) <= 59
    && Number(offsetHour) <= 23 && Number(offsetMinute) <= 59
}

function matches(schema, value, root, depth = 0) {
  if (depth > 64) return false
  if (schema.$ref) {
    const definition = root.$defs?.[schema.$ref.split('/').at(-1)]
    return definition !== undefined && matches(definition, value, root, depth + 1)
  }
  if (schema.anyOf && !schema.anyOf.some((option) => matches(option, value, root, depth + 1))) return false
  if (schema.enum && !schema.enum.includes(value)) return false
  if (schema.const !== undefined && schema.const !== value) return false
  switch (schema.type) {
    case 'null': if (value !== null) return false; break
    case 'boolean': if (typeof value !== 'boolean') return false; break
    case 'integer': if (!Number.isSafeInteger(value)) return false; break
    case 'number': if (typeof value !== 'number' || !Number.isFinite(value)) return false; break
    case 'string':
      if (typeof value !== 'string') return false
      if (schema.minLength !== undefined && [...value].length < schema.minLength) return false
      if (schema.maxLength !== undefined && [...value].length > schema.maxLength) return false
      if (schema.pattern && !new RegExp(schema.pattern).test(value)) return false
      if (schema.format === 'date-time' && !timestamp(value)) return false
      break
    case 'array':
      if (!Array.isArray(value) || !value.every((item) => matches(schema.items, item, root, depth + 1))) return false
      break
    case 'object': {
      if (value === null || typeof value !== 'object' || Array.isArray(value)) return false
      if (Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null) return false
      if ((schema.required ?? []).some((key) => !own(value, key))) return false
      for (const [key, child] of Object.entries(value)) {
        if (schema.propertyNames && !matches(schema.propertyNames, key, root, depth + 1)) return false
        if (own(schema.properties ?? {}, key)) {
          if (!matches(schema.properties[key], child, root, depth + 1)) return false
        } else if (schema.additionalProperties === false) return false
        else if (schema.additionalProperties && !matches(schema.additionalProperties, child, root, depth + 1)) return false
      }
      if (schema.title === 'PublicProfile' && !contractSchema.unverified_stages.includes(value.setup_stage) && value.owner_id === null) return false
      break
    }
    default: break
  }
  if (typeof value === 'number') {
    if (schema.minimum !== undefined && value < schema.minimum) return false
    if (schema.maximum !== undefined && value > schema.maximum) return false
  }
  if (schema['x-native-payload']) {
    if (!nonsecretPayload(value)) return false
    if (new TextEncoder().encode(JSON.stringify(value)).length > contractSchema.native_payload_max_bytes) return false
  }
  return true
}

/** Validate JSON data from the public boundary. Unknown/internal contracts fail closed.
 * @param {string} name
 * @param {unknown} value
 * @returns {boolean}
 */
export function validateContract(name, value) {
  if (!own(contractSchema.contracts, name)) return false
  try {
    return matches(contractSchema.contracts[name], value, contractSchema.contracts[name])
  } catch {
    return false
  }
}

/** Reject a malformed public DTO before a consumer uses it.
 * @param {string} name
 * @param {unknown} value
 * @returns {unknown}
 */
export function assertContract(name, value) {
  if (!validateContract(name, value)) throw new TypeError(`Invalid ${name} contract`)
  return value
}
