"""Generate browser CSS from the packaged native/browser art source."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / "src/tg_assistant/desktop/design_tokens.json"
OUTPUT = ROOT / "dashboard-prototype/src/design-tokens.css"


def render() -> str:
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))
    values = {**tokens["colors"], "paper-2": tokens["colors"]["panel"]}
    lines = ["/* Generated by scripts/generate_design_tokens.py. Do not hand-edit. */", ":root {"]
    lines.extend(f"  --{name}: {value};" for name, value in values.items())
    lines.extend(f"  --font-{role}: {tokens['fonts'][role + '_css']};" for role in ("display", "ui"))
    geometry = tokens["geometry"]
    lines.extend([
        f"  --line: {geometry['border']}px solid var(--ink);",
        f"  --shadow: {geometry['shadow']}px {geometry['shadow']}px 0 var(--ink);",
        f"  --target: {geometry['target']}px;",
        f"  --radius: {geometry['radius']}px;", "}", "",
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("Browser design token mirror is stale; run scripts/generate_design_tokens.py")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
